name: TCPlugin
version: ${project.version}
main: me.nathan.tcplugin.TcPlugin
api-version: 1.16
authors: [LaSpruca]
description: The offical technocraft plugin
website: qrl.nz
commands:
  givebaton:
    usage: /givebaton [player]
    description: Gives a player a TCPD batton, brrr
  discord:
    usage: /discord
    description: Gives you the Technocraft Discord Information
  bee:
    usage: According to all known laws of aviation, there is no way that a bee should be able to fly.
    description: According to all known laws of aviation, there is no way that a bee should be able to fly.
